name = str(input("your name:"))
branch = str(input("your branch:"))
gender = str(input("your gender:"))
college = str(input("your college:"))
age = int(input("your age:"))
print("Name:",name,end ='\n')
print("Branch:",branch,end ='\n')
print("Gender:",gender,end ='\n')
print("College:",college,end ='\n')
print("Age:",age)
